version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - mern
    restart: unless-stopped

  backend:
    build: ./backend
    ports: 
      - "5050:5050"
    networks:
      - mern
    depends_on:
      - mongodb
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongodb:27017/employee

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - mern
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

networks:
  mern:
    driver: bridge

volumes:
  mongo-data:
    driver: local

